/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "j2534.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(opendiag_Empty, opendiag_Empty, AUTO)


PB_BIND(opendiag_Target, opendiag_Target, AUTO)


PB_BIND(opendiag_Object, opendiag_Object, AUTO)


PB_BIND(opendiag_Config, opendiag_Config, AUTO)


PB_BIND(opendiag_Message, opendiag_Message, 4)


PB_BIND(opendiag_Connect, opendiag_Connect, AUTO)


PB_BIND(opendiag_LogicalConnect, opendiag_LogicalConnect, AUTO)


PB_BIND(opendiag_Queue, opendiag_Queue, 4)


PB_BIND(opendiag_Periodic, opendiag_Periodic, 4)


PB_BIND(opendiag_Filter, opendiag_Filter, AUTO)


PB_BIND(opendiag_Voltage, opendiag_Voltage, AUTO)


PB_BIND(opendiag_Ioctl, opendiag_Ioctl, 2)


PB_BIND(opendiag_Select, opendiag_Select, AUTO)


PB_BIND(opendiag_Request, opendiag_Request, 4)


PB_BIND(opendiag_ProtocolLimit, opendiag_ProtocolLimit, AUTO)


PB_BIND(opendiag_Capabilities, opendiag_Capabilities, AUTO)


PB_BIND(opendiag_Response, opendiag_Response, 4)



