/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_OPENDIAG_J2534_PB_H_INCLUDED
#define PB_OPENDIAG_J2534_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _opendiag_Empty {
    char dummy_field;
} opendiag_Empty;

typedef struct _opendiag_Target {
    uint32_t id;
} opendiag_Target;

typedef struct _opendiag_Object {
    uint32_t channel;
    uint32_t id;
} opendiag_Object;

typedef struct _opendiag_Config {
    uint32_t parameter;
    uint32_t value;
} opendiag_Config;

typedef PB_BYTES_ARRAY_T(4128) opendiag_Message_data_t;
typedef struct _opendiag_Message {
    uint32_t protocol;
    uint32_t handle;
    uint32_t rx_status;
    uint32_t tx_flags;
    uint32_t timestamp_us;
    uint32_t extra_data_index;
    opendiag_Message_data_t data;
} opendiag_Message;

typedef struct _opendiag_Connect {
    uint32_t device;
    uint32_t protocol;
    uint32_t flags;
    uint32_t baudrate;
    uint32_t connector;
    pb_size_t pins_count;
    uint32_t pins[2];
} opendiag_Connect;

typedef PB_BYTES_ARRAY_T(5) opendiag_LogicalConnect_local_address_t;
typedef PB_BYTES_ARRAY_T(5) opendiag_LogicalConnect_remote_address_t;
typedef struct _opendiag_LogicalConnect {
    uint32_t physical;
    uint32_t protocol;
    uint32_t flags;
    uint32_t local_flags;
    uint32_t remote_flags;
    opendiag_LogicalConnect_local_address_t local_address;
    opendiag_LogicalConnect_remote_address_t remote_address;
} opendiag_LogicalConnect;

typedef struct _opendiag_Queue {
    uint32_t channel;
    bool has_message;
    opendiag_Message message;
} opendiag_Queue;

typedef struct _opendiag_Periodic {
    uint32_t channel;
    uint32_t interval_ms;
    bool has_message;
    opendiag_Message message;
} opendiag_Periodic;

typedef PB_BYTES_ARRAY_T(12) opendiag_Filter_mask_t;
typedef PB_BYTES_ARRAY_T(12) opendiag_Filter_pattern_t;
typedef struct _opendiag_Filter {
    uint32_t channel;
    uint32_t type;
    uint32_t flags;
    opendiag_Filter_mask_t mask;
    opendiag_Filter_pattern_t pattern;
} opendiag_Filter;

typedef struct _opendiag_Voltage {
    uint32_t device;
    uint32_t connector;
    uint32_t pin;
    uint32_t millivolts;
} opendiag_Voltage;

typedef PB_BYTES_ARRAY_T(255) opendiag_Ioctl_data_t;
typedef struct _opendiag_Ioctl {
    uint32_t target;
    uint32_t id;
    pb_size_t config_count;
    opendiag_Config config[32];
    opendiag_Ioctl_data_t data;
    uint32_t connector;
    uint32_t pin;
} opendiag_Ioctl;

typedef struct _opendiag_Select {
    uint32_t type;
    pb_size_t channels_count;
    uint32_t channels[5];
} opendiag_Select;

typedef struct _opendiag_Request {
    pb_size_t which_command;
    union {
        opendiag_Empty capabilities;
        opendiag_Empty open;
        opendiag_Target close;
        opendiag_Connect connect;
        opendiag_Target disconnect;
        opendiag_Target read;
        opendiag_Periodic start_periodic;
        opendiag_Object stop_periodic;
        opendiag_Filter start_filter;
        opendiag_Object stop_filter;
        opendiag_Voltage voltage;
        opendiag_Target version;
        opendiag_Empty last_error;
        opendiag_Ioctl ioctl;
        opendiag_Queue queue;
        opendiag_LogicalConnect logical_connect;
        opendiag_Target logical_disconnect;
        opendiag_Select select;
    } command;
} opendiag_Request;

typedef struct _opendiag_ProtocolLimit {
    uint32_t protocol;
    uint32_t max_tx_data;
    uint32_t max_rx_data;
} opendiag_ProtocolLimit;

typedef struct _opendiag_Capabilities {
    uint32_t wire_version;
    uint32_t api_version;
    uint32_t physical_channels;
    uint32_t logical_channels;
    uint32_t filters_per_channel;
    uint32_t periodic_per_channel;
    uint32_t fragment_bytes;
    uint32_t rpc_bytes;
    uint32_t rx_queue_bytes;
    uint32_t tx_queue_messages;
    pb_size_t protocols_count;
    opendiag_ProtocolLimit protocols[6];
    bool full_j2534_compliance;
} opendiag_Capabilities;

typedef PB_BYTES_ARRAY_T(255) opendiag_Response_data_t;
typedef struct _opendiag_Response {
    uint32_t status;
    uint32_t id;
    uint32_t count;
    bool has_message;
    opendiag_Message message;
    pb_size_t config_count;
    opendiag_Config config[32];
    opendiag_Response_data_t data;
    pb_size_t channels_count;
    uint32_t channels[5];
    char text[128];
    bool has_capabilities;
    opendiag_Capabilities capabilities;
    uint32_t millivolts;
} opendiag_Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define opendiag_Empty_init_default              {0}
#define opendiag_Target_init_default             {0}
#define opendiag_Object_init_default             {0, 0}
#define opendiag_Config_init_default             {0, 0}
#define opendiag_Message_init_default            {0, 0, 0, 0, 0, 0, {0, {0}}}
#define opendiag_Connect_init_default            {0, 0, 0, 0, 0, 0, {0, 0}}
#define opendiag_LogicalConnect_init_default     {0, 0, 0, 0, 0, {0, {0}}, {0, {0}}}
#define opendiag_Queue_init_default              {0, false, opendiag_Message_init_default}
#define opendiag_Periodic_init_default           {0, 0, false, opendiag_Message_init_default}
#define opendiag_Filter_init_default             {0, 0, 0, {0, {0}}, {0, {0}}}
#define opendiag_Voltage_init_default            {0, 0, 0, 0}
#define opendiag_Ioctl_init_default              {0, 0, 0, {opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default}, {0, {0}}, 0, 0}
#define opendiag_Select_init_default             {0, 0, {0, 0, 0, 0, 0}}
#define opendiag_Request_init_default            {0, {opendiag_Empty_init_default}}
#define opendiag_ProtocolLimit_init_default      {0, 0, 0}
#define opendiag_Capabilities_init_default       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {opendiag_ProtocolLimit_init_default, opendiag_ProtocolLimit_init_default, opendiag_ProtocolLimit_init_default, opendiag_ProtocolLimit_init_default, opendiag_ProtocolLimit_init_default, opendiag_ProtocolLimit_init_default}, 0}
#define opendiag_Response_init_default           {0, 0, 0, false, opendiag_Message_init_default, 0, {opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default, opendiag_Config_init_default}, {0, {0}}, 0, {0, 0, 0, 0, 0}, "", false, opendiag_Capabilities_init_default, 0}
#define opendiag_Empty_init_zero                 {0}
#define opendiag_Target_init_zero                {0}
#define opendiag_Object_init_zero                {0, 0}
#define opendiag_Config_init_zero                {0, 0}
#define opendiag_Message_init_zero               {0, 0, 0, 0, 0, 0, {0, {0}}}
#define opendiag_Connect_init_zero               {0, 0, 0, 0, 0, 0, {0, 0}}
#define opendiag_LogicalConnect_init_zero        {0, 0, 0, 0, 0, {0, {0}}, {0, {0}}}
#define opendiag_Queue_init_zero                 {0, false, opendiag_Message_init_zero}
#define opendiag_Periodic_init_zero              {0, 0, false, opendiag_Message_init_zero}
#define opendiag_Filter_init_zero                {0, 0, 0, {0, {0}}, {0, {0}}}
#define opendiag_Voltage_init_zero               {0, 0, 0, 0}
#define opendiag_Ioctl_init_zero                 {0, 0, 0, {opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero}, {0, {0}}, 0, 0}
#define opendiag_Select_init_zero                {0, 0, {0, 0, 0, 0, 0}}
#define opendiag_Request_init_zero               {0, {opendiag_Empty_init_zero}}
#define opendiag_ProtocolLimit_init_zero         {0, 0, 0}
#define opendiag_Capabilities_init_zero          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {opendiag_ProtocolLimit_init_zero, opendiag_ProtocolLimit_init_zero, opendiag_ProtocolLimit_init_zero, opendiag_ProtocolLimit_init_zero, opendiag_ProtocolLimit_init_zero, opendiag_ProtocolLimit_init_zero}, 0}
#define opendiag_Response_init_zero              {0, 0, 0, false, opendiag_Message_init_zero, 0, {opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero, opendiag_Config_init_zero}, {0, {0}}, 0, {0, 0, 0, 0, 0}, "", false, opendiag_Capabilities_init_zero, 0}

/* Field tags (for use in manual encoding/decoding) */
#define opendiag_Target_id_tag                   1
#define opendiag_Object_channel_tag              1
#define opendiag_Object_id_tag                   2
#define opendiag_Config_parameter_tag            1
#define opendiag_Config_value_tag                2
#define opendiag_Message_protocol_tag            1
#define opendiag_Message_handle_tag              2
#define opendiag_Message_rx_status_tag           3
#define opendiag_Message_tx_flags_tag            4
#define opendiag_Message_timestamp_us_tag        5
#define opendiag_Message_extra_data_index_tag    6
#define opendiag_Message_data_tag                7
#define opendiag_Connect_device_tag              1
#define opendiag_Connect_protocol_tag            2
#define opendiag_Connect_flags_tag               3
#define opendiag_Connect_baudrate_tag            4
#define opendiag_Connect_connector_tag           5
#define opendiag_Connect_pins_tag                6
#define opendiag_LogicalConnect_physical_tag     1
#define opendiag_LogicalConnect_protocol_tag     2
#define opendiag_LogicalConnect_flags_tag        3
#define opendiag_LogicalConnect_local_flags_tag  4
#define opendiag_LogicalConnect_remote_flags_tag 5
#define opendiag_LogicalConnect_local_address_tag 6
#define opendiag_LogicalConnect_remote_address_tag 7
#define opendiag_Queue_channel_tag               1
#define opendiag_Queue_message_tag               2
#define opendiag_Periodic_channel_tag            1
#define opendiag_Periodic_interval_ms_tag        2
#define opendiag_Periodic_message_tag            3
#define opendiag_Filter_channel_tag              1
#define opendiag_Filter_type_tag                 2
#define opendiag_Filter_flags_tag                3
#define opendiag_Filter_mask_tag                 4
#define opendiag_Filter_pattern_tag              5
#define opendiag_Voltage_device_tag              1
#define opendiag_Voltage_connector_tag           2
#define opendiag_Voltage_pin_tag                 3
#define opendiag_Voltage_millivolts_tag          4
#define opendiag_Ioctl_target_tag                1
#define opendiag_Ioctl_id_tag                    2
#define opendiag_Ioctl_config_tag                3
#define opendiag_Ioctl_data_tag                  4
#define opendiag_Ioctl_connector_tag             5
#define opendiag_Ioctl_pin_tag                   6
#define opendiag_Select_type_tag                 1
#define opendiag_Select_channels_tag             2
#define opendiag_Request_capabilities_tag        1
#define opendiag_Request_open_tag                2
#define opendiag_Request_close_tag               3
#define opendiag_Request_connect_tag             4
#define opendiag_Request_disconnect_tag          5
#define opendiag_Request_read_tag                6
#define opendiag_Request_start_periodic_tag      8
#define opendiag_Request_stop_periodic_tag       9
#define opendiag_Request_start_filter_tag        10
#define opendiag_Request_stop_filter_tag         11
#define opendiag_Request_voltage_tag             12
#define opendiag_Request_version_tag             13
#define opendiag_Request_last_error_tag          14
#define opendiag_Request_ioctl_tag               15
#define opendiag_Request_queue_tag               16
#define opendiag_Request_logical_connect_tag     19
#define opendiag_Request_logical_disconnect_tag  20
#define opendiag_Request_select_tag              21
#define opendiag_ProtocolLimit_protocol_tag      1
#define opendiag_ProtocolLimit_max_tx_data_tag   2
#define opendiag_ProtocolLimit_max_rx_data_tag   3
#define opendiag_Capabilities_wire_version_tag   1
#define opendiag_Capabilities_api_version_tag    2
#define opendiag_Capabilities_physical_channels_tag 3
#define opendiag_Capabilities_logical_channels_tag 4
#define opendiag_Capabilities_filters_per_channel_tag 5
#define opendiag_Capabilities_periodic_per_channel_tag 6
#define opendiag_Capabilities_fragment_bytes_tag 7
#define opendiag_Capabilities_rpc_bytes_tag      8
#define opendiag_Capabilities_rx_queue_bytes_tag 9
#define opendiag_Capabilities_tx_queue_messages_tag 10
#define opendiag_Capabilities_protocols_tag      11
#define opendiag_Capabilities_full_j2534_compliance_tag 12
#define opendiag_Response_status_tag             1
#define opendiag_Response_id_tag                 2
#define opendiag_Response_count_tag              3
#define opendiag_Response_message_tag            4
#define opendiag_Response_config_tag             5
#define opendiag_Response_data_tag               6
#define opendiag_Response_channels_tag           7
#define opendiag_Response_text_tag               8
#define opendiag_Response_capabilities_tag       9
#define opendiag_Response_millivolts_tag         10

/* Struct field encoding specification for nanopb */
#define opendiag_Empty_FIELDLIST(X, a) \

#define opendiag_Empty_CALLBACK NULL
#define opendiag_Empty_DEFAULT NULL

#define opendiag_Target_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define opendiag_Target_CALLBACK NULL
#define opendiag_Target_DEFAULT NULL

#define opendiag_Object_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           1) \
X(a, STATIC,   SINGULAR, UINT32,   id,                2)
#define opendiag_Object_CALLBACK NULL
#define opendiag_Object_DEFAULT NULL

#define opendiag_Config_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   parameter,         1) \
X(a, STATIC,   SINGULAR, UINT32,   value,             2)
#define opendiag_Config_CALLBACK NULL
#define opendiag_Config_DEFAULT NULL

#define opendiag_Message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol,          1) \
X(a, STATIC,   SINGULAR, UINT32,   handle,            2) \
X(a, STATIC,   SINGULAR, UINT32,   rx_status,         3) \
X(a, STATIC,   SINGULAR, UINT32,   tx_flags,          4) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_us,      5) \
X(a, STATIC,   SINGULAR, UINT32,   extra_data_index,   6) \
X(a, STATIC,   SINGULAR, BYTES,    data,              7)
#define opendiag_Message_CALLBACK NULL
#define opendiag_Message_DEFAULT NULL

#define opendiag_Connect_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   device,            1) \
X(a, STATIC,   SINGULAR, UINT32,   protocol,          2) \
X(a, STATIC,   SINGULAR, UINT32,   flags,             3) \
X(a, STATIC,   SINGULAR, UINT32,   baudrate,          4) \
X(a, STATIC,   SINGULAR, UINT32,   connector,         5) \
X(a, STATIC,   REPEATED, UINT32,   pins,              6)
#define opendiag_Connect_CALLBACK NULL
#define opendiag_Connect_DEFAULT NULL

#define opendiag_LogicalConnect_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   physical,          1) \
X(a, STATIC,   SINGULAR, UINT32,   protocol,          2) \
X(a, STATIC,   SINGULAR, UINT32,   flags,             3) \
X(a, STATIC,   SINGULAR, UINT32,   local_flags,       4) \
X(a, STATIC,   SINGULAR, UINT32,   remote_flags,      5) \
X(a, STATIC,   SINGULAR, BYTES,    local_address,     6) \
X(a, STATIC,   SINGULAR, BYTES,    remote_address,    7)
#define opendiag_LogicalConnect_CALLBACK NULL
#define opendiag_LogicalConnect_DEFAULT NULL

#define opendiag_Queue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           2)
#define opendiag_Queue_CALLBACK NULL
#define opendiag_Queue_DEFAULT NULL
#define opendiag_Queue_message_MSGTYPE opendiag_Message

#define opendiag_Periodic_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           1) \
X(a, STATIC,   SINGULAR, UINT32,   interval_ms,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           3)
#define opendiag_Periodic_CALLBACK NULL
#define opendiag_Periodic_DEFAULT NULL
#define opendiag_Periodic_message_MSGTYPE opendiag_Message

#define opendiag_Filter_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           1) \
X(a, STATIC,   SINGULAR, UINT32,   type,              2) \
X(a, STATIC,   SINGULAR, UINT32,   flags,             3) \
X(a, STATIC,   SINGULAR, BYTES,    mask,              4) \
X(a, STATIC,   SINGULAR, BYTES,    pattern,           5)
#define opendiag_Filter_CALLBACK NULL
#define opendiag_Filter_DEFAULT NULL

#define opendiag_Voltage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   device,            1) \
X(a, STATIC,   SINGULAR, UINT32,   connector,         2) \
X(a, STATIC,   SINGULAR, UINT32,   pin,               3) \
X(a, STATIC,   SINGULAR, UINT32,   millivolts,        4)
#define opendiag_Voltage_CALLBACK NULL
#define opendiag_Voltage_DEFAULT NULL

#define opendiag_Ioctl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   target,            1) \
X(a, STATIC,   SINGULAR, UINT32,   id,                2) \
X(a, STATIC,   REPEATED, MESSAGE,  config,            3) \
X(a, STATIC,   SINGULAR, BYTES,    data,              4) \
X(a, STATIC,   SINGULAR, UINT32,   connector,         5) \
X(a, STATIC,   SINGULAR, UINT32,   pin,               6)
#define opendiag_Ioctl_CALLBACK NULL
#define opendiag_Ioctl_DEFAULT NULL
#define opendiag_Ioctl_config_MSGTYPE opendiag_Config

#define opendiag_Select_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1) \
X(a, STATIC,   REPEATED, UINT32,   channels,          2)
#define opendiag_Select_CALLBACK NULL
#define opendiag_Select_DEFAULT NULL

#define opendiag_Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,capabilities,command.capabilities),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,open,command.open),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,close,command.close),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,connect,command.connect),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,disconnect,command.disconnect),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,read,command.read),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,start_periodic,command.start_periodic),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,stop_periodic,command.stop_periodic),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,start_filter,command.start_filter),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,stop_filter,command.stop_filter),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,voltage,command.voltage),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,version,command.version),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,last_error,command.last_error),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,ioctl,command.ioctl),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,queue,command.queue),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,logical_connect,command.logical_connect),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,logical_disconnect,command.logical_disconnect),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,select,command.select),  21)
#define opendiag_Request_CALLBACK NULL
#define opendiag_Request_DEFAULT NULL
#define opendiag_Request_command_capabilities_MSGTYPE opendiag_Empty
#define opendiag_Request_command_open_MSGTYPE opendiag_Empty
#define opendiag_Request_command_close_MSGTYPE opendiag_Target
#define opendiag_Request_command_connect_MSGTYPE opendiag_Connect
#define opendiag_Request_command_disconnect_MSGTYPE opendiag_Target
#define opendiag_Request_command_read_MSGTYPE opendiag_Target
#define opendiag_Request_command_start_periodic_MSGTYPE opendiag_Periodic
#define opendiag_Request_command_stop_periodic_MSGTYPE opendiag_Object
#define opendiag_Request_command_start_filter_MSGTYPE opendiag_Filter
#define opendiag_Request_command_stop_filter_MSGTYPE opendiag_Object
#define opendiag_Request_command_voltage_MSGTYPE opendiag_Voltage
#define opendiag_Request_command_version_MSGTYPE opendiag_Target
#define opendiag_Request_command_last_error_MSGTYPE opendiag_Empty
#define opendiag_Request_command_ioctl_MSGTYPE opendiag_Ioctl
#define opendiag_Request_command_queue_MSGTYPE opendiag_Queue
#define opendiag_Request_command_logical_connect_MSGTYPE opendiag_LogicalConnect
#define opendiag_Request_command_logical_disconnect_MSGTYPE opendiag_Target
#define opendiag_Request_command_select_MSGTYPE opendiag_Select

#define opendiag_ProtocolLimit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol,          1) \
X(a, STATIC,   SINGULAR, UINT32,   max_tx_data,       2) \
X(a, STATIC,   SINGULAR, UINT32,   max_rx_data,       3)
#define opendiag_ProtocolLimit_CALLBACK NULL
#define opendiag_ProtocolLimit_DEFAULT NULL

#define opendiag_Capabilities_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   wire_version,      1) \
X(a, STATIC,   SINGULAR, UINT32,   api_version,       2) \
X(a, STATIC,   SINGULAR, UINT32,   physical_channels,   3) \
X(a, STATIC,   SINGULAR, UINT32,   logical_channels,   4) \
X(a, STATIC,   SINGULAR, UINT32,   filters_per_channel,   5) \
X(a, STATIC,   SINGULAR, UINT32,   periodic_per_channel,   6) \
X(a, STATIC,   SINGULAR, UINT32,   fragment_bytes,    7) \
X(a, STATIC,   SINGULAR, UINT32,   rpc_bytes,         8) \
X(a, STATIC,   SINGULAR, UINT32,   rx_queue_bytes,    9) \
X(a, STATIC,   SINGULAR, UINT32,   tx_queue_messages,  10) \
X(a, STATIC,   REPEATED, MESSAGE,  protocols,        11) \
X(a, STATIC,   SINGULAR, BOOL,     full_j2534_compliance,  12)
#define opendiag_Capabilities_CALLBACK NULL
#define opendiag_Capabilities_DEFAULT NULL
#define opendiag_Capabilities_protocols_MSGTYPE opendiag_ProtocolLimit

#define opendiag_Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   status,            1) \
X(a, STATIC,   SINGULAR, UINT32,   id,                2) \
X(a, STATIC,   SINGULAR, UINT32,   count,             3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           4) \
X(a, STATIC,   REPEATED, MESSAGE,  config,            5) \
X(a, STATIC,   SINGULAR, BYTES,    data,              6) \
X(a, STATIC,   REPEATED, UINT32,   channels,          7) \
X(a, STATIC,   SINGULAR, STRING,   text,              8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  capabilities,      9) \
X(a, STATIC,   SINGULAR, UINT32,   millivolts,       10)
#define opendiag_Response_CALLBACK NULL
#define opendiag_Response_DEFAULT NULL
#define opendiag_Response_message_MSGTYPE opendiag_Message
#define opendiag_Response_config_MSGTYPE opendiag_Config
#define opendiag_Response_capabilities_MSGTYPE opendiag_Capabilities

extern const pb_msgdesc_t opendiag_Empty_msg;
extern const pb_msgdesc_t opendiag_Target_msg;
extern const pb_msgdesc_t opendiag_Object_msg;
extern const pb_msgdesc_t opendiag_Config_msg;
extern const pb_msgdesc_t opendiag_Message_msg;
extern const pb_msgdesc_t opendiag_Connect_msg;
extern const pb_msgdesc_t opendiag_LogicalConnect_msg;
extern const pb_msgdesc_t opendiag_Queue_msg;
extern const pb_msgdesc_t opendiag_Periodic_msg;
extern const pb_msgdesc_t opendiag_Filter_msg;
extern const pb_msgdesc_t opendiag_Voltage_msg;
extern const pb_msgdesc_t opendiag_Ioctl_msg;
extern const pb_msgdesc_t opendiag_Select_msg;
extern const pb_msgdesc_t opendiag_Request_msg;
extern const pb_msgdesc_t opendiag_ProtocolLimit_msg;
extern const pb_msgdesc_t opendiag_Capabilities_msg;
extern const pb_msgdesc_t opendiag_Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define opendiag_Empty_fields &opendiag_Empty_msg
#define opendiag_Target_fields &opendiag_Target_msg
#define opendiag_Object_fields &opendiag_Object_msg
#define opendiag_Config_fields &opendiag_Config_msg
#define opendiag_Message_fields &opendiag_Message_msg
#define opendiag_Connect_fields &opendiag_Connect_msg
#define opendiag_LogicalConnect_fields &opendiag_LogicalConnect_msg
#define opendiag_Queue_fields &opendiag_Queue_msg
#define opendiag_Periodic_fields &opendiag_Periodic_msg
#define opendiag_Filter_fields &opendiag_Filter_msg
#define opendiag_Voltage_fields &opendiag_Voltage_msg
#define opendiag_Ioctl_fields &opendiag_Ioctl_msg
#define opendiag_Select_fields &opendiag_Select_msg
#define opendiag_Request_fields &opendiag_Request_msg
#define opendiag_ProtocolLimit_fields &opendiag_ProtocolLimit_msg
#define opendiag_Capabilities_fields &opendiag_Capabilities_msg
#define opendiag_Response_fields &opendiag_Response_msg

/* Maximum encoded size of messages (where known) */
#define OPENDIAG_J2534_PB_H_MAX_SIZE             opendiag_Response_size
#define opendiag_Capabilities_size               182
#define opendiag_Config_size                     12
#define opendiag_Connect_size                    42
#define opendiag_Empty_size                      0
#define opendiag_Filter_size                     46
#define opendiag_Ioctl_size                      730
#define opendiag_LogicalConnect_size             44
#define opendiag_Message_size                    4167
#define opendiag_Object_size                     12
#define opendiag_Periodic_size                   4182
#define opendiag_ProtocolLimit_size              18
#define opendiag_Queue_size                      4176
#define opendiag_Request_size                    4185
#define opendiag_Response_size                   5245
#define opendiag_Select_size                     36
#define opendiag_Target_size                     6
#define opendiag_Voltage_size                    24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
