#!/usr/bin/env python3
"""Derive the driver version from the repository tag, as the firmware's PROJECT_VER does."""
import argparse
from pathlib import Path
import re
import subprocess
import sys

FIELD_MAX = 65535


def describe(project):
    """ESP-IDF derives PROJECT_VER with the same command, so both halves agree."""
    try:
        output = subprocess.check_output(["git", "describe", "--always", "--tags", "--dirty"],
                                         cwd=project, stderr=subprocess.DEVNULL, text=True)
    except (OSError, subprocess.CalledProcessError):
        return ""
    return output.strip()


def fields(tag):
    """v1.0.2 -> (1, 0, 2, 0); v1.0.2-5-gabc1234 -> (1, 0, 2, 5); untagged -> zeros.

    VERSIONINFO fields are 16-bit, so an absurd tag clamps rather than overflowing.
    """
    match = re.match(r"^v?(\d+)\.(\d+)\.(\d+)(?:-(\d+)-g[0-9a-f]+)?", tag)
    if not match:
        return (0, 0, 0, 0)
    return tuple(min(int(part or 0), FIELD_MAX) for part in match.groups())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    arguments = parser.parse_args()
    project = Path(__file__).resolve().parents[2]
    tag = describe(project)
    if not tag:
        tag = "unknown"
        print("warning: no git version available; building as unknown", file=sys.stderr)
    major, minor, patch, build = fields(tag)
    contents = ("// Generated by tools/version.py from the repository tag. Do not edit.\n"
                "#pragma once\n"
                f"#define OPENDIAG_VERSION_FIELDS {major},{minor},{patch},{build}\n"
                f'#define OPENDIAG_VERSION_STRING "{major}.{minor}.{patch}.{build}"\n'
                f'#define OPENDIAG_VERSION_TAG "{tag}"\n')
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    # Rewrite only on change so a fixed HEAD does not force rebuilds.
    if not arguments.output.exists() or arguments.output.read_text() != contents:
        arguments.output.write_text(contents)


if __name__ == "__main__":
    main()
